### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by ll7** [athackst/vscode_ros2_workspace#1]
Hi, thank you for providing this template and your blog posts regarding vscode, docker and ros2. I am very inexperienced but wanted to try out your template. I was uncertain whether to `docker pull` your stock template or to `git clone` and `docker build .devcontainer/`. I was wondering if you could clarify what advantages both options have for novice docker users. I guess it's easier to modify your template if it's a source controlled repository?

**Comment by athackst** [comment]
Good question!

This is a [template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) which means you can copy its contents in a new repository, without forking it, and VSCode will build the container for you.

## How this works

### Prerequisites

You should already have Docker and VSCode with the remote containers plugin installed on your system.

* [docker](https://docs.docker.com/engine/install/) on your system
* [vscode](https://code.visualstudio.com/)
* [vscode remote containers plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)

### Get the template

Click on "use this template"

![template_use](https://user-images.githubusercontent.com/6098197/91331899-43f23b80-e780-11ea-92c8-b4665ce126f1.png)

### Create your repository

On the next dialog, name the repository you would like to start and decide if you want all of the branches, or just the latest LTS: Foxy.

![template_new](https://user-images.githubusercontent.com/6098197/91332035-713ee980-e780-11ea-81d3-13b170f568b0.png)

Github will then create a new repository with the contents of this one in your account.  It grabs the latest changes as "initial commit".

### Clone your repo

Now you can clone your repo as normal

![template_download](https://user-images.githubusercontent.com/6098197/91332342-e4e0f680-e780-11ea-9525-49b0afa0e4bb.png)

### Open it in vscode

Now that you've cloned your repo onto your computer, you can open it in VSCode (File->Open Folder). 

When you open it for the first time, you should see a little popup that asks you if you would like to open it in a container.  Say yes!

![template_vscode](https://user-images.githubusercontent.com/6098197/91332551-36898100-e781-11ea-9080-729964373719.png)

If you don't see the pop-up, click on the little green square in the bottom left corner, which should bring up the container dialog

![template_vscode_bottom](https://user-images.githubusercontent.com/6098197/91332638-5d47b780-e781-11ea-9fb6-4d134dbfc464.png)

In the dialog, select "Remote Containers: Reopen in container"

VSCode will build the dockerfile inside of `.devcontainer` for you.  If you open a terminal inside VSCode (Terminal->New Terminal), you should see that your username has been changed to `ros`, and the bottom left green corner should say "Dev Container"

![template_container](https://user-images.githubusercontent.com/6098197/91332895-adbf1500-e781-11ea-8afc-7a22a5340d4a.png)

**Comment by ll7** [comment]
Thank you, this is very helpful. I was able to install `ros-foxy-turtlesim`, but was uncertain whether to use `apt` or `apt-get`.

Long term goal is to run Carla and Autoware or ASLAN in containers, but that's a stretch goal ;-)

**Comment by athackst** [comment]
Oh, I think I understand. You're wondering how you install more things with the template?

If you're extending the dockerfile, it's general practice to use `apt-get` instead of `apt`, but you're free to use whichever you prefer in the terminal.

### But I want to use more/different packages!

There are a couple of ways you can poke around with this IDE and ros2.  Pick the use case that most closely resembles your goals.

1. I want to download some packages and run them.  Just to kick the wheels and see what they do.

    You can install new packages within the containers terminal.  This will put them in the container environment VSCode is using.  It will stick around, even if you open and close the container, but will disapear if you rebuild the container.

2.  I want to download some code and run it!

    You should clone the code into the `src` directory.  Once you've done that, you can install all of the packages that depend on your downloaded code, as identified in its `package.xml` file.  (Tasks->Run Task->install dependencies). 

3. I want to add packages to a standard setup, cache it, and share it. Or, the packages I want to depend on for building aren't in the ROS ecosystem.  Or they are some how special.

    You should add additional installation/setup steps to `.devcontaienr/Dockerfile`.
