### ISSUE TITLE
Editing workspace files as a non-root containerUser or remoteUser

### ISSUE THREAD

**Issue by phillipov** [athackst/vscode_ros2_workspace#12]
Have you found a way to edit and save workspace files while connected to the development container with a **non-root user**? I want to use `"containerUser": "ros"` and `"remoteUser": "ros"`, but if I edit and save a file (such as `.devcontainer/Dockerfile`), I get a "permission denied" error from VS Code.

![devcontainer_eaccess](https://user-images.githubusercontent.com/41978078/138545368-ec55e702-97bc-441c-9799-79fce733e290.png)

This would really help me edit-and-test repeatedly without using a root user in the devcontainer.

**My host environment:** Ubuntu 20.04, VS Code 1.61.2, and Docker 20.10.9 in rootless mode with `dockerd-rootless-setuptool.sh`.

VS Code is still remapping the UID/GID of the `ros` user to match my host user. I think it's part of a more general Docker issue: all bind mounts are owned by `root` within the container. I'm still holding out hope that you ran into a solution :slightly_smiling_face:

```
ros@<my_machine>:~/vscode_ros2_workspace$ ls -l
total 20
-rw-rw-r-- 1 root root 11357 Oct 19 05:51 LICENSE
-rw-rw-r-- 1 root root  3997 Oct 19 05:51 README.md
drwxrwxr-x 2 root root  4096 Oct 19 05:51 src
#            ^ all owned by root!
```

I can use `"overrideCommand": true` and a custom entrypoint that `chown`s the bind mount then switches to a non-root user. This forces me to use `"containerUser": "root"`, though. Not a super pleasant workaround.

By the way, your ROSWorld talk on this development strategy was awesome!

**Comment by athackst** [comment]
Looks like maybe you cloned the repo using sudo?
