### ISSUE TITLE
Starting Docker from the terminal

### ISSUE THREAD

**Issue by aalbaali** [athackst/vscode_ros2_workspace#13]
Hi @athackst,

Thank you for this great package! It's been very helpful.

I am able to run the Docker container from VSCode without any issues, and I'm able to use the terminal within the container from VSCode. However, I would like to open the container from an external terminal (i.e., not VSCode), but I couldn't figure out the Docker command.

I'm expecting something along the lines of `docker exec -it -e DISPLAY=$DISPLAY <container-name> /bin/sh -c <some-commands>`, but I couldn't get the right combination. Would you happen to know what commands to insert so I have a similar bash terminal to the one within VSCode?

Thanks for your help!

Amro

**Comment by athackst** [comment]
I think the full command would be something like:

`docker exec -it -u ros --network=host --cap-add=SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined --volume=/tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY <container name> /bin/bash`

If you just want the terminal

`docker exec -it -u ros --network=host <contianer name> /bin/bash`

**Comment by aalbaali** [comment]
Thanks for the info @athackst. I was able to start the Docker container, but it's not quite the same thing done in VSCode (e.g., the colors are the not the same). But I guess this will suffice for now, so I'll close this ticket.

Thanks for your help :)
