### ISSUE TITLE
OpenGL error

### ISSUE THREAD

**Issue by relffok** [athackst/vscode_ros2_workspace#18]
Hi there, I'm actively using this template for ros2 development and I ran into an issue with presumably OpenGL.
I realized that rviz does not work anymore using all the dockerfiles from 03/22 on, crashing with the following: 

```
[ERROR] [1650546553.554378445] [rviz2]: rviz::RenderSystem: error creating render window: InvalidParametersException: Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /tmp/binarydeb/ros-galactic-rviz-ogre-vendor-8.5.0/obj-x86_64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1061)
[ERROR] [1650546553.554383907] [rviz2]: Unable to create the rendering window after 100 tries
```

So I installed `mesa-utils` checked if I can run `glxgears` which did also crash so I compared to an earlier image (from february) and compared the OpenGL versions inside the docker: 

```
FROM althack/ros2:galactic-gazebo-2022-02-01
glxinfo | grep "OpenGL version"
OpenGL version string: 3.1 Mesa 21.0.3
-> rviz and glxgears work
```

```
FROM althack/ros2:galactic-gazebo-2022-04-01
glxinfo | grep "OpenGL version"
OpenGL version string: 1.3 Mesa 21.2.6
-> rviz and glxgears crash
```

I'm not quite sure what causes these version changes, maybe you have an idea? 

Note: This might also rather belong in your dockerfiles repo depending on the fix.. sorry if this is misplaced!

**Comment by relffok** [comment]
Added `RUN echo "export LIBGL_ALWAYS_SOFTWARE=1" >> /home/ros/.bashrc` to the Dockerfile did the trick, though I am not sure why this is the case!

**Comment by athackst** [comment]
Thanks for the catch and the fix!

I added that variable to the devcontainer.json in #19  which should also work.  LMK if this solves your issue!

**Comment by relffok** [comment]
Yes it does and it makes more sense for the variable to be located in `devcontainer.json`!
I'm still a little confused how the two docker images resulted in a descending version. Can this result out of changed dependencies of ros2 packages? Do you have an insight for me?

**Comment by athackst** [comment]
Yes, it's likely due to a changed dependency inside of the ros2 packages.  I haven't changed the packages included in the dockerfile in some time.  It rebuilds pulling the latest each month and saves it with a tag.  I had found the tagging useful due to some ABI incompatibility issues with ROS packages in the past, so folks can always pin to an older version if they're in prod.

My best guess is that it might have something to do with this https://community.gazebosim.org/t/a-new-era-for-gazebo/1356 @chapulina for ideas on how to root cause this?

**Comment by chapulina** [comment]
Humm that doesn't look familiar to me. Since it happens to RViz as well, chances are it's not an issue with Gazebo. We haven't started migrating any Ignition debian packages to the new name yet, so I doubt that's related. Hope this helps.
