### ISSUE TITLE
Great Repository, ideas for OpenGL on Nvidia Drivier support

### ISSUE THREAD

**Issue by jensakut** [athackst/vscode_ros2_workspace#2]
Hi Athackst, 

first of all, thank you very much for this template. For me it works like a charm.

I needed openGL support for rqt graph, ros2 nav and other applications in the docker image on a nvidia videocard. 
To achieve this, I have allowed access to the xserver of the host and added some runArgs to the devcontainer.json. 

Is that something I should add to your repository as a PR? I would suggest just adding the necessary lines commented out and describing how to activate in the readme.md file, since the solution results in a host-specific container and may not apply to non-nvidia-driver systems. 

What do you think? 

BR Jens

**Comment by athackst** [comment]
Sounds good to me!  Feel free to make a PR

**Comment by jensakut** [comment]
Here it is: 
https://github.com/athackst/vscode_ros2_workspace/pull/3 

Since the changes are host-specific (require nvidia-gpu), could you give me feedback whether you prefer more branches and clean files OR less branches and the user has to comment in/out lines which will be error-prone..
