### ISSUE TITLE
How about a template without Docker

### ISSUE THREAD

**Issue by RaviBeagle** [athackst/vscode_ros2_workspace#21]
How can I use this template without Docker ? Would be nice to have one such

Thanks 
Ravishankar

**Comment by athackst** [comment]
You should be able to use it without opening the container.  The only delta I can think of is the environment variables - meaning you may need to source your ROS install.

What errors are you running into?

**Comment by RaviBeagle** [comment]
I think there would be no errors if I used the package as it is. 

I am using ROS2 galactic on WSL2. I did a few adaptations:

1) Removed .devcontainer, .git and .github folders
2) Changing foxy to galactic in .vscode JSON files
3) Added --merge-install option to clean task otherwise there is an error like this:
[0.201s] ERROR:colcon:colcon build: The install directory 'install' was created with the layout 'merged'. Please remove the install directory, pick a different one or add the '--merge-install' option.

4) Edited package CMakeLists.txt file to build the node
find_package(rclcpp REQUIRED)
add_executable(helloworld_node src/helloworld_node.cpp)
ament_target_dependencies(helloworld_node rclcpp)
install(TARGETS
    helloworld_node
  DESTINATION lib/${PROJECT_NAME})

I

**Comment by athackst** [comment]
So sounds like it works as intended then

Pro tip: there's a branch for each release.  If you want something other than the latest LTS you need to select "include all branches" when you create a repo from the template to get them 

galactic: https://github.com/athackst/vscode_ros2_workspace/tree/galactic
