### ISSUE TITLE
Paths changed?

### ISSUE THREAD

**Issue by fwarmuth** [athackst/vscode_ros2_workspace#37]
Hey,
first: great work! This helped me to smoothen out my transition towards a more productive ROS2 setup!!
Problem:
https://github.com/athackst/vscode_ros2_workspace/blob/4d5e9b01bb63d2c16842bfb8184d63954b0d73c4/.vscode/launch.json#L20

For me, `colcon` installs the packages to a different place:
Changed the line to:
```
      "program": "${workspaceFolder}/install/${input:package}/lib/${input:package}/${input:program}",
```
Could you verify if it's worth a PR from my side?
Cheers

**Comment by athackst** [comment]
My setup uses the `--merge-install` flag which corresponds to the 'program' location in the launch.json file.

The other location is where the isolated install places programs.
