### ISSUE TITLE
add `source colcon-argcomplete.bash` somewhere

### ISSUE THREAD

**Issue by SubaruArai** [athackst/vscode_ros2_workspace#49]
I'd like to add tab completion for `colcon`.
It should be possible to do so by adding this line to the end of `.devcontainer/DockerFile`:

```DockerFile
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /home/ros/.bashrc
```

Is this a good approach?
It's my first time trying to develop in a devcontainer, so please tell me it there's a better solution.

**Comment by athackst** [comment]
Great idea, I added it to the base docker images so that they'd all benefit from this idea
