### ISSUE TITLE
Visual Studio Code break points not triggering

### ISSUE THREAD

**Issue by Bart-van-Ingen** [athackst/vscode_ros2_workspace#5]
Hello!

Thanks for this nice template!
I am trying to get the debug task to work with the break points of visual studio code. However I am only able to use them in the main function of the node...
Is there another step that I need to do in order to get it to work?

**Comment by athackst** [comment]
I'm not sure what you mean by you can only use them in the main function of the node. Do you have a failing example you can share?

Otherwise, you might want to try adding `"justMyCode": false` to the launch config

```json
    // Example launch of a python file
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
      "justMyCode": false
    },
```

**Comment by athackst** [comment]
You may also want to build with'--symlink-install'

It might be that the files you've placed your breakpoints aren't in the files being used at execution time.

**Comment by Bart-van-Ingen** [comment]
Hello! sorry for the late response.
In the end I found out that the build option of optimizing ensures that not all code is reachable anymore when debugging. Changing it to use the debug only flag has seemed to solve the problem!

**Comment by athackst** [comment]
Good to know!  Thanks for circling back on this.
