### ISSUE TITLE
vs code source control not showing checked out repos 

### ISSUE THREAD

**Issue by JKBehrens** [athackst/vscode_ros2_workspace#56]
Thanks for sharing this work! 

I configured my workspace in `ros2.repos` and cloned them via the setup task. The only problem is that they don't appear in the vs code source control tab. 

Do you know how I can add them? Is it a problem that they are technically inside another git repository?

Thank you in advance!

**Comment by athackst** [comment]
They are indeed other git repositories.  

If you add them as a submodule they should show up correctly.
