### ISSUE TITLE
Different Workspace Location

### ISSUE THREAD

**Issue by SomaGallai** [athackst/vscode_ros2_workspace#6]
Hey,

Thank you for creating this great repository! 

Is there a way to change the workspace location to be /home/ros/workspace on the docker container? I would like to ask as well what would be the best way to map a directory(on host) for the docker container that contains multiple ROS packages relying on each other? I am aware of the ros2.repos solution you have implemented but most of the packages I would like to use are private repositories and it makes it harder to automatise with the SSH keys.

**Comment by athackst** [comment]
Glad you figured it out!
