### ISSUE TITLE
Could not run ROS2 Python Launch Debug configuration

### ISSUE THREAD

**Issue by saravanan-palanisamy-thi** [athackst/vscode_ros2_workspace#65]
`{
 "name": "ROS: Launch",
 "type": "ros",
 "request": "launch",
 "target": "${workspaceFolder}/install/share/ixcom_driver/launch/ixcom_driver.launch.py"
}`

I get the following error,
ModuleNotFoundError: No module named 'ixcom_driver.ixcom_driver_publisher

**Comment by athackst** [comment]
Does it work if you run it in the integrated terminal?

**Comment by saravanan-palanisamy-thi** [comment]
Hello Allison Thackson, 
Thanks for your quick response. 

It does work in integrated terminal. 
Even with ROS extension, from the command palette, ROS: Launch works.

**Comment by athackst** [comment]
I'm having trouble reproducing the error.

Commonly ModuelNotFoundErrors have to do with an incorrect environment setup.  Maybe try adding a task that runs "source install/setup.bash"  in `.vscode/task.json`

```
        {
            "label": "source",
            "detail": "Source the install directory",
            "type": "shell",
            "command": "source install/setup.bash",
            "problemMatcher": []
        }
```

And add this as a `preLaunchTask` in your `launch.json` file

```
    { 
        "name": "ROS: Launch", 
        "type": "ros", 
        "request": "launch", 
        "preLaunchTask": "source",
        "target": "${workspaceFolder}/install/share/ixcom_driver/launch/ixcom_driver.launch.py" 
    }

**Comment by athackst** [comment]
Also, what version of the docker are you running?

**Comment by saravanan-palanisamy-thi** [comment]
I managed to run the vscode debugger for ROS. I think the problem was in the Pythonpath. 
Thank you for your support.
