### ISSUE TITLE
Question: Sourcing for tests in container

### ISSUE THREAD

**Issue by bearrito** [athackst/vscode_ros2_workspace#76]
Hello, Thanks for putting this and your article together. It's valuable. 

My company already has a fair amount of existing tooling.  I'm trying to modify what you do to match our workflow. We can't really use the ros extension as it's too opinionated. We build our own ros distro and create custom images so we pull our own base workspace in that way. 

I have a question about how you might be sourcing after a build.

Right now we populate a `.env` with paths to `src` so it will look like

```
PYTHONPATH=/workspaces/our_project/service`
```

My trouble seems to be about what to do when you need to source `../setup.bash` in particular we want test discovery to work

On the cli it's simple to `colcon build && source ../setup.bash` but I've never figured out a way to source once the container is running and the window loaded so that VSCode tooling picks it up.

**Comment by athackst** [comment]
You might want to try a [postCreateCommand](https://code.visualstudio.com/docs/devcontainers/create-dev-container#_rebuild) Or adding sourcing to the dockerfile itself

```
ARG WORKSPACE
RUN echo "if [ -f ${WORKSPACE}/install/setup.bash ]; then source ${WORKSPACE}/install/setup.bash; fi" >> /home/ros/.bashrc
```

**Comment by bearrito** [comment]
Thanks for the response. 

So in your workflows if you have a project with multi ROS packages say `foo` and `foo_msgs`, where `foo` depends on `foo_msgs` if you modify `foo_msgs`, you are then doing a full container rebuild? That's what I'm doing now but it always felt heavy. Alas, that seems to be solution most folks have converged on.

**Comment by athackst** [comment]
No, the container mounts the workspace. The container can be set up to
source setup.bash for terminals, or you can grab the env variables that
setup.bash makes and add them to your container.  If you change foo_msg, it
should grab the updated files/binaries since the paths are the same.
